@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
class Parser
class FoodItem
class Order
class OrderDriver
interface List
interface Collection
interface JSONsimple


JSONsimple <|-- Parser
Collection <|-- Order
Order <|-- Parser
FoodItem <|- Order
Parser <|-- OrderDriver

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

class AbstractCollection {
int something
something()
}

class FoodItem {
- name : String
- quntity : int
- price : float
}

class Order {
- status : String
- type : String
- foodList : ArrayList<foodItem>
- Date : long
- OrderID : int
- totalPrice : float
- sumPrice(foodList a) : float
- buildFoodList(FoodItem a) : void
}

class Parser {
+ parseJSONOrder() : Order
+ exportOrder() : void
}

class OrderDriver {

+ startIncomingOrder() : void
+ displayIncomingOrder() : void
+ completeIncomingOrder() : void
+ displayAll() : void
}


@enduml